name: KeepExperience
author: MintoD
version: 1.1.0
api: [1.0.0]
main: com.mintod.keepexperience.Main

commands:
  keepexperience:
    description: Toggle keep experience
    permission: keepexperience.toggle.cmd

permissions:
  keepexperience.toggle.cmd:
    description: Allow players to toggle keep experience
    default: op